registration_post:
    path: /registration
    controller: App\Controller\RegistrationController::createUser
    methods: [POST]

registration_get:
    path: /registration
    controller: App\Controller\RegistrationController::index
    methods: [GET]

profile:
    path: /profile
    controller: App\Controller\ProfileController::index